### ISSUE TITLE
Inline Keyboard Paginate

### ISSUE THREAD

**Issue by Aazerra** [alexandercerutti/node-telegram-keyboard-wrapper#3]
### Paginate Keyboard
Hello
if the inline keyboard has a function to paginate keyboard buttons is good
if you can please add this option
this option is a useful and good option for too many keyboard buttons
I have 60 buttons and I need to paginate this keyboard if I add this option to my bot I share code to you

**Comment by alexandercerutti** [comment]
Hi, @TahaPY 
Pagination is not a thing for this library but should be a combination of this and `bot.editMessageReplyMarkup`. You should create a key with unique page identifier to be passed to the callback_data parameter.

I suppose that, to have 60 buttons, you'll take your data from a database or sort of.
You should create and show a new keyboard everytime you click on a button AND when you summon the keyboard. 😊

**Comment by Aazerra** [comment]
oh ok, ty for the answer <3 @alexandercerutti

**Comment by alexandercerutti** [comment]
You are welcome! For anything else, just ask in a new issue. If you need help with your bot, you can refer to the Telegram group. See here: https://github.com/yagop/node-telegram-bot-api/issues/721
